disable = [
  "MD013", # 行太长
  "MD033", # 允许 HTML
  "MD036", # 允许强调当标题
  "MD041", # 不强制第一行必须是 H1
  "MD024", # 允许重复标题
  "MD076", # 不检查列表空行
  "MD057", # 不检查本地链接是否存在
]

exclude = [
  "public",
  "node_modules"
]
